### ISSUE TITLE
Transliterate Z Norm error

### ISSUE THREAD

**Issue by chanmratekoko** [google/myanmar-tools#34]
Current behavior

class : TransliterateZNorm.java
method : convert 

input (zawgyi)
မၪၨဴရီ

Expected behavior
output (zawgyi)
မၪၨဴရီ

Actual Result
output (zawgyi)
မညၨဴရီ

**Comment by sffc** [comment]
@sven-oly can you take a look?  Seems like it is changing the U+106a to a U+100a for no reason.

**Comment by sven-oly** [comment]
Yes, this is a mistake. I'm working on the fix.
