### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by luminkhant** [google/myanmar-tools#37]
Wanna know there would be swift support for this project?

**Comment by sffc** [comment]
Follow the instructions in https://github.com/google/myanmar-tools#contributing-new-programming-language-support and I'll be happy to review a PR to add Swift language support. :smiley:

**Comment by lawinko** [comment]
Hi @luminkhant, If you are trying to implement in iOS or macOS projects, you can check on this https://github.com/lawinko/ZawgyiDetector.

**Comment by luminkhant** [comment]
Thanks for your contribution @lawinko

**Comment by bhamiltoncx** [comment]
I landed initial Swift support in https://github.com/google/myanmar-tools/pull/51 using the Swift Package Manager (SwiftPM).

The Swift library wraps the C++ library and can be built with `make client-swift`. You can run the tests with `make client-swift-test`.

Please note that until Swift 5.3, there is no real support for binary library dependencies in SwiftPM, so this support currently has a hack where it links the C++ library using `-rpath` to point to the absolute path in the build directory of `libmyanmartools.dylib`.

You can use `install_name_tool` to change this for your own product. [Here are some tips](https://medium.com/@donblas/fun-with-rpath-otool-and-install-name-tool-e3e41ae86172) on that.

**Comment by sffc** [comment]
Thanks to everyone who helped with this! I will close the issue as fixed.
