### ISSUE TITLE
Sync CLDR and Myanmar Tools conversion files

### ISSUE THREAD

**Issue by sffc** [google/myanmar-tools#69]
The Z/U conversion files are out of sync between CLDR and Myanmar Tools. It appears that the Myanmar Tools version is more up to date. We should reconcile the two versions and make sure that they stay in sync in the future.

https://github.com/google/myanmar-tools/commits/master/genconvert/input/my-t-my-d0-zawgyi.txt

https://github.com/unicode-org/cldr/commits/master/common/transforms/my-t-my-d0-zawgyi.xml

**Comment by sven-oly** [comment]
Do we have a CLDR ticket for this?

**Comment by sven-oly** [comment]
Should we set up a mechanism to check for differences with CLDR data files? Perhaps a github action?

**Comment by sven-oly** [comment]
Filed ticket https://unicode-org.atlassian.net/browse/CLDR-14854

**Comment by srl295** [comment]
CLDR side is marked done

**Comment by sffc** [comment]
Yes! https://github.com/unicode-org/cldr/pull/1667 is merged. The myanmar tools version was more up-to-date than the CLDR version, so there are no CLDR changes that need to be pulled in here. Closing as Fixed.
