### ISSUE TITLE
Unicode range is out of bound? or Is it valid empty space for unicode point A9FF?

### ISSUE THREAD

**Issue by ThutaNaing** [google/myanmar-tools#7]
[UA9E0.pdf](https://github.com/googlei18n/myanmar-tools/files/1898247/UA9E0.pdf)
According to Myanmar Extended-B (U+A9E0–U+A9FF) pdf, unicode range is start from A9E0 end at A9FE and found out A9FF is empty space. So Aren't we need to remove "A9FF" at all client code of ZawgyiUnicodeMarkovModel classes? Or is it still valid code point?

**Comment by sffc** [comment]
Thanks for the report.  For the purposes of the Zawgyi detection algorithm, code points like U+A9FF that have no data should not affect the detection result, so this change is not time-sensitive.  This change requires updating the binary data file, so it could be introduced along with the next version of the binary data file format.

**Comment by sffc** [comment]
I'm marking this as wontfix because making a change to the model is disruptive, and having unassigned code points in range is harmless to model accuracy.
