### ISSUE TITLE
Investigate fuzzer bug #35059

### ISSUE THREAD

**Issue by sffc** [google/myanmar-tools#87]
oss-fuzz filed the following report: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35059

CC @gnrunge @echeran -- are you interested in looking at this?  If not, I can put it on my plate.

**Comment by gnrunge** [comment]
Not at this time, sorry.
BTW, I don't have permission to view the findings.

Norbert

**Comment by echeran** [comment]
Yeah, similar to Norbert, I can't see the issue, and I should start taking a look at properties-related ICU bugs this week.

**Comment by sffc** [comment]
Here is the test case in bytes:

```
62 4E E9 BE E2 BA 00 00 00 EA A1 4D EA E1 80 A9 E2 00 41 00 00 00 00 00 EA E1 80 A9 E2 00 00 00 00 2E 00 00 00 00 00 00 00 00 3C A9 E9 EA E1 80 A9 E2 00 00 00 00 99 EA 99 00 00 00 00 41 00 00 00 00 00 EA E1 80 A9 E2 00 00 00 00 00 00 00 00 00 00 00 00 3C 4C 00 00 EA
```

Note that the string ends with a UTF-8 lead byte.  We should not read past the end of the string, but perhaps we should investigate.

**Comment by sffc** [comment]
oss-fuzz closed the issue with comment:

> ClusterFuzz testcase 4553018782646272 is flaky and no longer crashes, so closing issue.
